const starterPrompts = [
  // --- Original 100 ---
  { text: "_____ ROOM" }, { text: "_____ CAKE" }, { text: "_____ SCHOOL" }, { text: "_____ LIGHT" },
  { text: "_____ PHONE" }, { text: "_____ HOUSE" }, { text: "_____ WORK" }, { text: "_____ BALL" },
  { text: "_____ WATER" }, { text: "_____ BOARD" }, { text: "_____ ROAD" }, { text: "_____ TIME" },
  { text: "_____ BACK" }, { text: "_____ BOOK" }, { text: "_____ CARD" }, { text: "_____ CASE" },
  { text: "_____ DAY" }, { text: "_____ DOOR" }, { text: "_____ FIRE" }, { text: "_____ FISH" },
  { text: "_____ GLASS" }, { text: "_____ HAND" }, { text: "_____ HEAD" }, { text: "_____ KEY" },
  { text: "_____ LAND" }, { text: "_____ LIFE" }, { text: "_____ LINE" }, { text: "_____ MAN" },
  { text: "_____ MARK" }, { text: "_____ MATE" }, { text: "_____ NOTE" }, { text: "_____ OFFICE" },
  { text: "_____ PAPER" }, { text: "_____ PARK" }, { text: "_____ POINT" }, { text: "_____ POST" },
  { text: "_____ SIDE" }, { text: "_____ SPACE" }, { text: "_____ STAR" }, { text: "_____ TABLE" },
  { text: "_____ TOWN" }, { text: "_____ TREE" }, { text: "_____ WAY" }, { text: "_____ WORD" },
  { text: "_____ ZONE" }, { text: "_____ POWER" }, { text: "_____ SHOT" }, { text: "_____ NIGHT" },
  { text: "_____ NEWS" }, { text: "_____ MAIL" }, { text: "COLD _____" }, { text: "SOFT _____" },
  { text: "HARD _____" }, { text: "FAST _____" }, { text: "SLOW _____" }, { text: "HIGH _____" },
  { text: "LOW _____" }, { text: "DEEP _____" }, { text: "BLUE _____" }, { text: "RED _____" },
  { text: "BLACK _____" }, { text: "WHITE _____" }, { text: "GOLD _____" }, { text: "SILVER _____" },
  { text: "SWEET _____" }, { text: "SOUR _____" }, { text: "DRY _____" }, { text: "WET _____" },
  { text: "HOT _____" }, { text: "ICE _____" }, { text: "SEA _____" }, { text: "AIR _____" },
  { text: "SUN _____" }, { text: "MOON _____" }, { text: "STAR _____" }, { text: "ROCK _____" },
  { text: "WOOD _____" }, { text: "IRON _____" }, { text: "PAPER _____" }, { text: "GLASS _____" },
  { text: "SMART _____" }, { text: "DUMB _____" }, { text: "BIG _____" }, { text: "SMALL _____" },
  { text: "LITTLE _____" }, { text: "SUPER _____" }, { text: "MEGA _____" }, { text: "MICRO _____" },
  { text: "MINI _____" }, { text: "MAXI _____" }, { text: "WILD _____" }, { text: "SAFE _____" },
  { text: "FREE _____" }, { text: "FULL _____" }, { text: "EMPTY _____" }, { text: "OPEN _____" },
  { text: "CLOSE _____" }, { text: "EARLY _____" }, { text: "LATE _____" }, { text: "NEXT _____" },

  // --- Household & Food (Next 100) ---
  { text: "_____ CHAIR" }, { text: "_____ LAMP" }, { text: "_____ WINDOW" }, { text: "_____ SHELF" },
  { text: "_____ BOX" }, { text: "_____ BAG" }, { text: "_____ LOCK" }, { text: "_____ SOAP" },
  { text: "_____ TOWEL" }, { text: "_____ BED" }, { text: "_____ PILLOW" }, { text: "_____ CLOCK" },
  { text: "_____ WATCH" }, { text: "_____ MIRROR" }, { text: "_____ COMB" }, { text: "_____ BRUSH" },
  { text: "_____ BOWL" }, { text: "_____ PLATE" }, { text: "_____ FORK" }, { text: "_____ SPOON" },
  { text: "_____ KNIFE" }, { text: "_____ CUP" }, { text: "_____ MUG" }, { text: "_____ POT" },
  { text: "_____ PAN" }, { text: "_____ BOTTLE" }, { text: "_____ CAN" }, { text: "_____ LID" },
  { text: "_____ JAR" }, { text: "APPLE _____" }, { text: "ORANGE _____" }, { text: "BANANA _____" },
  { text: "CHERRY _____" }, { text: "GRAPE _____" }, { text: "MELON _____" }, { text: "BERRY _____" },
  { text: "CHOCOLATE _____" }, { text: "VANILLA _____" }, { text: "SUGAR _____" }, { text: "SALT _____" },
  { text: "PEPPER _____" }, { text: "HONEY _____" }, { text: "BUTTER _____" }, { text: "CHEESE _____" },
  { text: "BREAD _____" }, { text: "COOKIE _____" }, { text: "PIE _____" }, { text: "CANDY _____" },
  { text: "COFFEE _____" }, { text: "TEA _____" }, { text: "MILK _____" }, { text: "JUICE _____" },
  { text: "SODA _____" }, { text: "BEER _____" }, { text: "WINE _____" }, { text: "SOUP _____" },
  { text: "SALAD _____" }, { text: "STEAK _____" }, { text: "FISH _____" }, { text: "CHICKEN _____" },
  { text: "RAIN _____" }, { text: "SNOW _____" }, { text: "WIND _____" }, { text: "STORM _____" },
  { text: "DIRT _____" }, { text: "SAND _____" }, { text: "MUD _____" }, { text: "DUST _____" },
  { text: "MOUNTAIN _____" }, { text: "VALLEY _____" }, { text: "RIVER _____" }, { text: "LAKE _____" },
  { text: "OCEAN _____" }, { text: "BEACH _____" }, { text: "ISLAND _____" }, { text: "FOREST _____" },
  { text: "GARDEN _____" }, { text: "FLOWER _____" }, { text: "GRASS _____" }, { text: "LEAF _____" },
  { text: "SKY _____" }, { text: "CLOUD _____" }, { text: "PLANET _____" }, { text: "WORLD _____" },
  { text: "_____ TALK" }, { text: "_____ WALK" }, { text: "_____ RUN" }, { text: "_____ JUMP" },
  { text: "_____ PLAY" }, { text: "_____ STOP" }, { text: "_____ GO" }, { text: "_____ WAIT" },
  { text: "_____ GIVE" }, { text: "_____ TAKE" }, { text: "_____ KEEP" }, { text: "_____ SHOW" },
  { text: "_____ TELL" }, { text: "_____ READ" }, { text: "_____ WRITE" }, { text: "_____ SING" },

  // --- Professional & Travel (Next 100) ---
  { text: "_____ DANCE" }, { text: "_____ LAUGH" }, { text: "_____ SMILE" }, { text: "_____ CRY" },
  { text: "_____ CALL" }, { text: "_____ SEND" }, { text: "_____ LOOK" }, { text: "_____ HAPPY" },
  { text: "_____ SAD" }, { text: "_____ MAD" }, { text: "_____ COOL" }, { text: "_____ WARM" },
  { text: "_____ LONG" }, { text: "_____ SHORT" }, { text: "_____ LOUD" }, { text: "_____ QUIET" },
  { text: "_____ NEW" }, { text: "_____ OLD" }, { text: "_____ GOOD" }, { text: "_____ BAD" },
  { text: "_____ BEST" }, { text: "DRAGON _____" }, { text: "MONSTER _____" }, { text: "GHOST _____" },
  { text: "DREAM _____" }, { text: "MORNING _____" }, { text: "SUMMER _____" }, { text: "WINTER _____" },
  { text: "FALL _____" }, { text: "SPRING _____" }, { text: "LOVE _____" }, { text: "HATE _____" },
  { text: "LUCK _____" }, { text: "_____ TRIP" }, { text: "_____ BREAK" }, { text: "_____ FALL" },
  { text: "_____ RISE" }, { text: "_____ SET" }, { text: "_____ MIND" }, { text: "_____ HEART" },
  { text: "_____ SOUL" }, { text: "_____ BODY" }, { text: "_____ FOOT" }, { text: "_____ FACE" },
  { text: "_____ EYE" }, { text: "_____ NOSE" }, { text: "_____ EAR" }, { text: "_____ HAIR" },
  { text: "_____ SKIN" }, { text: "_____ BONE" }, { text: "_____ BLOOD" }, { text: "_____ BRAIN" },
  { text: "_____ NERVE" }, { text: "_____ VOICE" }, { text: "_____ SOUND" }, { text: "_____ COLOR" },
  { text: "_____ SHAPE" }, { text: "_____ SIZE" }, { text: "_____ WEIGHT" }, { text: "_____ DESK" },
  { text: "_____ FILE" }, { text: "_____ COMPUTER" }, { text: "_____ SCREEN" }, { text: "_____ MOUSE" },
  { text: "_____ CODE" }, { text: "_____ DATA" }, { text: "_____ WEB" }, { text: "_____ LINK" },
  { text: "_____ SITE" }, { text: "_____ PAGE" }, { text: "_____ BANK" }, { text: "_____ CASH" },
  { text: "_____ LOAN" }, { text: "_____ TAX" }, { text: "_____ BILL" }, { text: "_____ FORM" },
  { text: "_____ LIST" }, { text: "_____ CAR" }, { text: "_____ TRUCK" }, { text: "_____ BUS" },
  { text: "_____ TRAIN" }, { text: "_____ PLANE" }, { text: "_____ BOAT" }, { text: "_____ SHIP" },
  { text: "_____ BIKE" }, { text: "_____ TIRE" }, { text: "_____ WHEEL" }, { text: "_____ SEAT" },
  { text: "_____ BELT" }, { text: "_____ STREET" }, { text: "_____ LANE" }, { text: "_____ PATH" },
  { text: "_____ SIGN" }, { text: "_____ GAS" }, { text: "_____ OIL" }, { text: "_____ FUEL" },
  { text: "_____ TANK" }, { text: "_____ FILM" }, { text: "_____ ACT" }, { text: "_____ SCENE" },

  // --- Entertainment & Clothing (Next 100) ---
  { text: "_____ SONG" }, { text: "_____ BAND" }, { text: "_____ POP" }, { text: "_____ JAZZ" },
  { text: "_____ BEAT" }, { text: "_____ DRUM" }, { text: "_____ BAT" }, { text: "_____ NET" },
  { text: "_____ GOAL" }, { text: "_____ CLUB" }, { text: "_____ TEAM" }, { text: "_____ FAN" },
  { text: "_____ WIN" }, { text: "_____ HAT" }, { text: "_____ CAP" }, { text: "_____ SHIRT" },
  { text: "_____ COAT" }, { text: "_____ VEST" }, { text: "_____ PANT" }, { text: "_____ BOOT" },
  { text: "_____ SOCK" }, { text: "_____ GLOVE" }, { text: "_____ RING" }, { text: "_____ TIE" },
  { text: "_____ SILK" }, { text: "_____ WOOL" }, { text: "_____ DOG" }, { text: "_____ CAT" },
  { text: "_____ BIRD" }, { text: "_____ BEAR" }, { text: "_____ LION" }, { text: "_____ TIGER" },
  { text: "_____ WOLF" }, { text: "_____ HORSE" }, { text: "_____ COW" }, { text: "_____ PIG" },
  { text: "_____ DUCK" }, { text: "_____ BUG" }, { text: "_____ FLY" }, { text: "_____ BEE" },
  { text: "_____ ANT" }, { text: "_____ TAIL" }, { text: "_____ WING" }, { text: "_____ PAW" },
  { text: "_____ CLAW" }, { text: "SCHOOL _____" }, { text: "CHURCH _____" }, { text: "STATE _____" },
  { text: "CITY _____" }, { text: "HOME _____" }, { text: "FRONT _____" }, { text: "TOP _____" },
  { text: "BASE _____" }, { text: "UNDER _____" }, { text: "OVER _____" }, { text: "INNER _____" },
  { text: "OUTER _____" }, { text: "CROSS _____" }, { text: "MULTI _____" }, { text: "SEMI _____" },
  { text: "ANTI _____" }, { text: "PRO _____" }, { text: "ELECTRIC _____" }, { text: "SOLAR _____" },
  { text: "DIGITAL _____" }, { text: "VIRTUAL _____" }, { text: "REAL _____" }, { text: "PURE _____" },
  { text: "DIRTY _____" }, { text: "CLEAN _____" }, { text: "FRESH _____" }, { text: "LUCKY _____" },
  { text: "MAGIC _____" }, { text: "WONDER _____" }, { text: "NIGHTMARE _____" }, { text: "SECRET _____" },
  { text: "PUBLIC _____" }, { text: "PRIVATE _____" }, { text: "BRAVE _____" }, { text: "STRONG _____" },
  { text: "WEAK _____" }, { text: "BOLD _____" }, { text: "_____ BOMB" }, { text: "_____ BLAST" },
  { text: "_____ FLASH" }, { text: "_____ TRICK" }, { text: "_____ TREAT" }, { text: "_____ JOKE" },
  { text: "_____ GIFT" }, { text: "_____ PRIZE" }, { text: "_____ CHAMP" }, { text: "_____ HERO" },
  { text: "_____ BOSS" }, { text: "_____ QUEEN" }, { text: "_____ KING" }, { text: "_____ ACE" },
  { text: "_____ JOKER" }, { text: "_____ CRASH" }, { text: "_____ BOOM" }, { text: "_____ SNAP" },

  // --- Final Touches & Tricky Words (Final 100) ---
  { text: "_____ CRACK" }, { text: "_____ FIZZ" }, { text: "_____ BUZZ" }, { text: "_____ SHOCK" },
  { text: "_____ WAVE" }, { text: "_____ TIDE" }, { text: "_____ FLOW" }, { text: "_____ PEAK" },
  { text: "_____ HOLE" }, { text: "_____ SPOT" }, { text: "SILENT _____" }, { text: "HIDDEN _____" },
  { text: "BROKEN _____" }, { text: "FROZEN _____" }, { text: "DOUBLE _____" }, { text: "TRIPLE _____" },
  { text: "RANDOM _____" }, { text: "VINTAGE _____" }, { text: "_____ SERVER" }, { text: "_____ STREAM" },
  { text: "_____ TOKEN" }, { text: "_____ BUFFER" }, { text: "_____ SCRIPT" }, { text: "_____ GADGET" },
  { text: "_____ SIGNAL" }, { text: "_____ THUNDER" }, { text: "_____ SHADOW" }, { text: "_____ ECHO" },
  { text: "_____ MIRAGE" }, { text: "_____ CANYON" }, { text: "_____ RAPIDS" }, { text: "_____ BREEZE" },
  { text: "_____ CAPTAIN" }, { text: "_____ HARBOR" }, { text: "_____ BRIDGE" }, { text: "_____ TUNNEL" },
  { text: "_____ MUSEUM" }, { text: "_____ ROCKET" }, { text: "_____ JUNGLE" }, { text: "_____ DESERT" },
  { text: "_____ HOLD" }, { text: "_____ WARE" }, { text: "_____ GUM" }, { text: "_____ STICK" },
  { text: "_____ CANDLE" }, { text: "_____ WAX" }, { text: "_____ STRING" }, { text: "_____ ROPE" },
  { text: "_____ WIRE" }, { text: "_____ PIPE" }, { text: "_____ TUBE" }, { text: "_____ HOSE" },
  { text: "_____ PUMP" }, { text: "_____ VALVE" }, { text: "_____ GEAR" }, { text: "_____ BOLT" },
  { text: "_____ SCREW" }, { text: "_____ NAIL" }, { text: "_____ HAMMER" }, { text: "_____ DRILL" },
  { text: "_____ SAW" }, { text: "_____ BLADE" }, { text: "_____ EDGE" }, { text: "_____ POINT" },
  { text: "_____ SHARP" }, { text: "_____ BLUNT" }, { text: "_____ FLAT" }, { text: "_____ ROUND" },
  { text: "_____ SQUARE" }, { text: "_____ STAR" }, { text: "_____ HEART" }, { text: "_____ CROSS" },
  { text: "_____ CIRCLE" }, { text: "_____ OVAL" }, { text: "_____ SOLID" }, { text: "_____ LIQUID" },
  { text: "_____ GAS" }, { text: "_____ VAPOR" }, { text: "_____ STEAM" }, { text: "_____ MIST" },
  { text: "_____ FOG" }, { text: "_____ HAZE" }, { text: "_____ SMOKE" }, { text: "_____ ASH" },
  { text: "_____ COAL" }, { text: "_____ FUEL" }, { text: "_____ ENERGY" }, { text: "_____ LIGHT" },
  { text: "_____ DARK" }, { text: "_____ SHADE" }, { text: "_____ TINT" }, { text: "_____ GLOW" },
  { text: "_____ BEAM" }, { text: "_____ RAY" }, { text: "_____ WAVE" }, { text: "_____ PULSE" },
  { text: "_____ BEAT" }, { text: "_____ RHYTHM" }, { text: "_____ TEMPO" }, { text: "_____ PITCH" }
];

export default starterPrompts;
